"""Regression + chunking tests for GLiNER-based CV extraction.

Test suite
----------
test_cleanup_logic()
    Pure unit test for GLiNER post-processing (_clean_entities, noise filters,
    school redirect, interest cleanup, word-concatenation repair).
    Does NOT require the GLiNER package -- calls _clean_entities() directly.

test_chunking_unit()
    Unit test for _build_chunks().  Verifies chunk count, size bounds, and
    overlap without loading the GLiNER model.

test_chunking_before_after()
    Requires GLiNER.  Builds a long synthetic CV text with known entities in
    the SECOND HALF (beyond ~384 tokens).  Compares entity counts extracted by
    the old single-pass approach vs. the new chunked approach.
    Expected: chunked >= single-pass, and the late-document landmark entities
    (AIRBUS, THALES, BOUYGUES, Universite Paris-Saclay) are found.

test_gliner_unit()
    Short raw-text extraction smoke test (requires GLiNER).

test_pipeline_two_column()
    Full pipeline integration on cv_two_column.pdf (requires fitz).

test_pipeline_one_column()
    Regression on cv_one_column.pdf (requires fitz).

test_pipeline_long_cv()
    Full pipeline integration on cv_long.pdf generated by make_long_cv().
    Verifies that the chunked extractor finds the late-document entities.

test_fallback_without_gliner()
    Verifies USE_GLINER=false falls back to regex without crashing.

Run:
    cd backend
    python scripts/test_gliner_extraction.py

Exit code 0 = all checks passed, 1 = at least one failure.
"""
from __future__ import annotations

import importlib.util
import os
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
BACKEND = os.path.abspath(os.path.join(HERE, ".."))
if BACKEND not in sys.path:
    sys.path.insert(0, BACKEND)

# Regenerate fixtures on demand
spec = importlib.util.spec_from_file_location(
    "_make_test_cvs", os.path.join(HERE, "_make_test_cvs.py")
)
_mk = importlib.util.module_from_spec(spec)
spec.loader.exec_module(_mk)

FIXTURES = os.path.join(BACKEND, "tests", "fixtures")
TWO_COL = os.path.join(FIXTURES, "cv_two_column.pdf")
ONE_COL = os.path.join(FIXTURES, "cv_one_column.pdf")
LONG_CV = os.path.join(FIXTURES, "cv_long.pdf")

_failures: list[str] = []


def check(cond: bool, msg: str) -> None:
    status = "PASS" if cond else "FAIL"
    print(f"  [{status}] {msg}")
    if not cond:
        _failures.append(msg)


# ---------------------------------------------------------------------------
# Check GLiNER availability before running model-dependent tests
# ---------------------------------------------------------------------------

def _gliner_importable() -> bool:
    try:
        import gliner  # noqa: F401
        return True
    except ImportError:
        return False


GLINER_PRESENT = _gliner_importable()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _name_matches(extracted: str | None, first: str, last: str) -> bool:
    """Case-insensitive check that both first and last name tokens appear."""
    if not extracted:
        return False
    lower = extracted.lower()
    return first.lower() in lower and last.lower() in lower


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

def test_cleanup_logic():
    """Post-processing unit test: uses synthetic (mock) GLiNER output.

    Does NOT require the GLiNER package to be installed -- it calls
    _clean_entities() directly.  Validates:
      - '##' BERT artifacts are removed
      - fragments with < 3 alpha chars ('Li') and short non-acronyms ('Esp')
        are removed
      - school-like company spans (ESUP, Universite Sorbonne) are moved to
        education, not kept in companies
      - interests do not contain the candidate name or a section header
    """
    print("\n=== GLiNER cleanup unit test (no model needed) ===")

    from ai_module.nlp.gliner_extractor import GLiNERExtractor

    extractor = GLiNERExtractor()

    mock_entities = [
        # --- person name ---
        {"label": "person name", "text": "Raphael MARTIN"},

        # --- companies: 3 real + 4 pollutants ---
        {"label": "company", "text": "DIOR"},
        {"label": "company", "text": "ORANGE"},
        {"label": "company", "text": "DANONE"},
        {"label": "company", "text": "ESUP"},
        {"label": "company", "text": "Universite Sorbonne"},
        {"label": "company", "text": "Esp"},
        {"label": "company", "text": "Li"},
        {
            "label": "company",
            "text": "##cence Pro Commerce et Distribution E",
        },

        # --- schools (GLiNER-labeled) ---
        {"label": "school", "text": "Universite Sorbonne"},
        {"label": "school", "text": "ESUP"},

        # --- interests: 1 valid + 2 pollutants ---
        {"label": "interest", "text": "Raphael MARTIN"},
        {"label": "interest", "text": "INTITULE DU POSTE / STAGE"},
        {"label": "interest", "text": "Voyage"},
    ]

    result = extractor._clean_entities(mock_entities)
    print(f"  full_name  : {result.get('full_name')!r}")
    print(f"  companies  : {result.get('companies')}")
    print(f"  education  : {result.get('education')}")
    print(f"  job_titles : {result.get('job_titles')}")
    print(f"  interests  : {result.get('interests')}")

    companies = result.get("companies", [])
    education = result.get("education", [])
    interests = result.get("interests", [])
    full_name = result.get("full_name")

    check(
        _name_matches(full_name, "Raphael", "Martin"),
        f"cleanup: full_name is Raphael MARTIN (got {full_name!r})",
    )

    for co in ("DIOR", "ORANGE", "DANONE"):
        check(co in companies, f"cleanup: '{co}' kept in companies (got {companies})")

    check(
        "ESUP" not in companies,
        f"cleanup: 'ESUP' NOT in companies (got {companies})",
    )
    check(
        not any("Sorbonne" in c or "sorbonne" in c.lower() for c in companies),
        f"cleanup: 'Universite Sorbonne' NOT in companies (got {companies})",
    )
    check(
        not any(c.startswith("##") for c in companies),
        f"cleanup: no '##' artifacts in companies (got {companies})",
    )
    check(
        not any(c in ("Esp", "Li") for c in companies),
        f"cleanup: short fragments not in companies (got {companies})",
    )

    check(
        any("Sorbonne" in e or "sorbonne" in e.lower() for e in education),
        f"cleanup: 'Universite Sorbonne' in education (got {education})",
    )
    check(
        any("ESUP" in e or "esup" in e.lower() for e in education),
        f"cleanup: 'ESUP' in education (got {education})",
    )

    check(
        "Voyage" in interests,
        f"cleanup: valid interest 'Voyage' kept (got {interests})",
    )
    check(
        not any((full_name or "").lower() == i.lower() for i in interests),
        f"cleanup: candidate name NOT in interests (got {interests})",
    )
    check(
        not any("INTITULE" in i.upper() or "/" in i for i in interests),
        f"cleanup: form label NOT in interests (got {interests})",
    )

    # --- word-concatenation fix ---
    from ai_module.nlp.gliner_extractor import GLiNERExtractor as _G
    _ext = _G()
    fused_cases = [
        ("Voyageen sac a dos",      "Voyage en sac a dos"),
        ("Theatreet concerts",      "Theatre et concerts"),
        ("Cuisinedu jour",          "Cuisine du jour"),
        ("Randonnee",               "Randonnee"),
        ("Benevola",                "Benevola"),
        ("Voyage en sac a dos",     "Voyage en sac a dos"),
    ]
    for fused, expected in fused_cases:
        got = _ext._fix_concatenated_words(fused)
        check(
            got == expected,
            f"concat fix: {fused!r} -> {got!r} (expected {expected!r})",
        )
    fused_mock_extra = [
        {"label": "person name", "text": "Test User"},
        {"label": "interest", "text": "Voyageen sac a dos"},
        {"label": "interest", "text": "Randonnee"},
    ]
    fused_result = _ext._clean_entities(fused_mock_extra)
    check(
        any("Voyage" in i and " en" in i for i in fused_result.get("interests", [])),
        f"concat e2e: 'Voyageen sac a dos' repaired in pipeline "
        f"(interests={fused_result.get('interests')})",
    )
    check(
        "Randonnee" in fused_result.get("interests", []),
        f"concat e2e: 'Randonnee' unchanged (interests={fused_result.get('interests')})",
    )


def test_chunking_unit():
    """Unit test for _build_chunks() -- no model loading required.

    Verifies:
    - A short text produces exactly 1 chunk.
    - A long text (many lines) produces multiple chunks, each within the
      _CHUNK_TOKENS budget (char-based estimate since no tokenizer is loaded).
    - The number of chunks is capped at _MAX_CHUNKS.
    - Consecutive chunks share overlapping lines (the overlap mechanism works).
    - The concatenation of all unique lines covers the entire input.
    """
    print("\n=== Chunking unit test (no model needed) ===")

    from ai_module.nlp.gliner_extractor import (
        GLiNERExtractor, _CHUNK_TOKENS, _CHUNK_OVERLAP_TOKENS,
        _MAX_CHUNKS, _CHARS_PER_TOKEN,
    )

    extractor = GLiNERExtractor()
    # Model is NOT loaded in this test; _build_chunks falls back to char-based counting.

    # ---- Test 1: short text -> 1 chunk ----
    short_text = "Jean DUPONT\nIngenieur Logiciel\njean.dupont@email.com\n"
    chunks = extractor._build_chunks(short_text)
    check(len(chunks) == 1, f"short text: expected 1 chunk, got {len(chunks)}")
    check(
        short_text.strip() in chunks[0].strip(),
        f"short text: chunk must contain the original text",
    )

    # ---- Test 2: empty text -> graceful handling ----
    chunks_empty = extractor._build_chunks("")
    check(
        chunks_empty == [] or (len(chunks_empty) == 1 and chunks_empty[0] == ""),
        f"empty text: graceful handling (got {chunks_empty!r})",
    )

    # ---- Test 3: long text -> multiple chunks, all within budget ----
    # Generate lines that are 20 chars each; with _CHARS_PER_TOKEN=4 each line
    # is ~5 tokens.  _CHUNK_TOKENS=340 -> ~68 lines per chunk.
    # 600 lines -> ~600/68 ~ 9 chunks (after overlap).
    long_lines = [
        f"Experience senior chef projet entreprise numero {i:03d} annee 2000"
        for i in range(600)
    ]
    long_text = "\n".join(long_lines) + "\n"
    chunks = extractor._build_chunks(long_text)

    check(len(chunks) > 1, f"long text: expected >1 chunk, got {len(chunks)}")
    check(
        len(chunks) <= _MAX_CHUNKS,
        f"long text: at most {_MAX_CHUNKS} chunks, got {len(chunks)}",
    )

    # Each chunk must fit within _CHUNK_TOKENS (char-estimate; allow +1 for the
    # overlap line that may slightly exceed the budget by one line's worth).
    budget_chars = (_CHUNK_TOKENS + 10) * _CHARS_PER_TOKEN
    for i, ch in enumerate(chunks):
        check(
            len(ch) <= budget_chars,
            f"chunk {i}: len={len(ch)} chars <= budget {budget_chars} chars",
        )

    # ---- Test 4: overlap -- consecutive chunks share lines ----
    if len(chunks) >= 2:
        lines_c0 = set(chunks[0].splitlines())
        lines_c1 = set(chunks[1].splitlines())
        shared = lines_c0 & lines_c1
        check(
            len(shared) > 0,
            f"overlap: chunks 0-1 share at least 1 line (shared={len(shared)})",
        )

    # ---- Test 5: full coverage -- no line from the original is lost ----
    # (Applies only when we don't hit _MAX_CHUNKS, otherwise late lines are
    # intentionally dropped to bound runtime.)
    if len(chunks) < _MAX_CHUNKS:
        all_chunk_content = "".join(chunks)
        # Every original line must appear somewhere across the chunks.
        # We check a sample (first, middle, last line before the cap).
        sample_lines = [long_lines[0], long_lines[len(long_lines) // 2], long_lines[-1]]
        for sample in sample_lines:
            check(
                sample in all_chunk_content,
                f"coverage: line {sample!r} present in chunks",
            )
    else:
        print(f"  [INFO] Hit _MAX_CHUNKS cap ({_MAX_CHUNKS}); late lines intentionally dropped.")

    # ---- Test 6: cap is enforced ----
    # Very long text (10 000 lines) must never exceed _MAX_CHUNKS.
    huge_lines = [f"ligne {i} du document" for i in range(10000)]
    huge_text = "\n".join(huge_lines) + "\n"
    chunks_huge = extractor._build_chunks(huge_text)
    check(
        len(chunks_huge) <= _MAX_CHUNKS,
        f"huge text: cap enforced, got {len(chunks_huge)} chunks (max {_MAX_CHUNKS})",
    )

    # ---- Test 7: name priority -- chunk-0 entities come first ----
    # Simulate merged entity list: same word-count names from chunk 0 and chunk 5.
    # chunk-0 name must win the tiebreak.
    name_chunk0 = "Alice MARTIN"   # 2 words, chunk 0
    name_chunk5 = "Bob DUPONT"     # 2 words, chunk 5 (same length)
    mock_names_merged = [
        {"label": "person name", "text": name_chunk0},
        {"label": "person name", "text": name_chunk5},
    ]
    result_name = extractor._clean_entities(mock_names_merged)
    check(
        result_name.get("full_name") == name_chunk0,
        f"name priority: chunk-0 name wins tie "
        f"(got {result_name.get('full_name')!r}, expected {name_chunk0!r})",
    )


def test_chunking_before_after():
    """Before/after comparison: chunked GLiNER vs legacy single-pass.

    Builds a LONG synthetic CV text (> 1000 tokens) with known entities
    deliberately placed in the second half (beyond ~384 tokens).

    Without chunking, those entities would be truncated and missed.
    With chunking, they must all be found.

    Requires GLiNER to be installed and the model to be loadable.
    """
    print("\n=== Chunking before/after entity count (requires GLiNER) ===")

    if not GLINER_PRESENT:
        print("  [SKIP] gliner package not installed -- skipping before/after test")
        return

    from ai_module.nlp.gliner_extractor import GLiNERExtractor, _LABELS

    extractor = GLiNERExtractor()
    if not extractor._load_model():
        print("  [SKIP] GLiNER model could not be loaded -- skipping")
        return

    # Build a synthetic CV text where the EARLY part is dense filler and
    # the LATE part contains the landmark entities.
    # Each line ~60 chars ~ 15 tokens.  We need ~30 filler lines to reach
    # ~450 tokens (safely past the 384-token truncation point).
    filler_lines = [
        "Chef de projet senior responsable de la coordination des equipes et du suivi"
        f" des livrables techniques et fonctionnels pour le compte du client numero {i}."
        for i in range(35)
    ]
    landmark_lines = [
        "",
        "MISSIONS RECENTES",
        "Consultant technique -- AIRBUS OPERATIONS SAS  (2024, mission 6 mois)",
        "Audit du process de verification logicielle pour le programme A320neo.",
        "",
        "Consultant -- THALES GROUP AVIONICS  (2023, mission 4 mois)",
        "Architecture des calculateurs de mission pour drone de surveillance.",
        "",
        "Expert -- BOUYGUES TELECOM  (2022, mission 3 mois)",
        "Securisation des firmwares equipements reseau CPE.",
        "",
        "FORMATION",
        "Master Recherche -- Universite Paris-Saclay  (2007)",
        "Diplome Ingenieur -- INSA Toulouse  (2005)",
        "",
        "CENTRES D INTERET",
        "Pilote ULM",
        "Escalade en falaise",
    ]

    long_cv_text = "\n".join(filler_lines + landmark_lines)

    # ----- BEFORE: legacy single-pass on first 6000 chars -----
    t0 = time.time()
    raw_before = extractor.__class__._model.predict_entities(
        long_cv_text[:6000], _LABELS, threshold=0.45
    )
    t_before = time.time() - t0
    result_before = extractor._clean_entities(raw_before)

    companies_before = result_before.get("companies", [])
    education_before = result_before.get("education", [])
    n_ents_before = (
        len(companies_before)
        + len(education_before)
        + len(result_before.get("job_titles", []))
        + len(result_before.get("interests", []))
    )

    print(f"  BEFORE (single-pass, {t_before:.2f}s):")
    print(f"    companies  : {companies_before}")
    print(f"    education  : {education_before}")
    print(f"    job_titles : {result_before.get('job_titles', [])}")
    print(f"    interests  : {result_before.get('interests', [])}")
    print(f"    total entities: {n_ents_before}")

    # ----- AFTER: chunked extraction -----
    t0 = time.time()
    result_after = extractor.extract(long_cv_text)
    t_after = time.time() - t0

    companies_after = result_after.get("companies", [])
    education_after = result_after.get("education", [])
    n_ents_after = (
        len(companies_after)
        + len(education_after)
        + len(result_after.get("job_titles", []))
        + len(result_after.get("interests", []))
    )

    print(f"  AFTER  (chunked,      {t_after:.2f}s):")
    print(f"    companies  : {companies_after}")
    print(f"    education  : {education_after}")
    print(f"    job_titles : {result_after.get('job_titles', [])}")
    print(f"    interests  : {result_after.get('interests', [])}")
    print(f"    total entities: {n_ents_after}")

    # ----- Assertions -----
    check(
        n_ents_after >= n_ents_before,
        f"after >= before: {n_ents_after} >= {n_ents_before} total entities",
    )

    companies_after_upper = " ".join(c.upper() for c in companies_after)
    check(
        "AIRBUS" in companies_after_upper,
        f"chunked: AIRBUS found in late-document companies (got {companies_after})",
    )
    check(
        "THALES" in companies_after_upper,
        f"chunked: THALES found in late-document companies (got {companies_after})",
    )
    check(
        "BOUYGUES" in companies_after_upper,
        f"chunked: BOUYGUES found in late-document companies (got {companies_after})",
    )

    education_after_str = " ".join(e.lower() for e in education_after)
    check(
        "saclay" in education_after_str or "paris" in education_after_str,
        f"chunked: Universite Paris-Saclay found in education (got {education_after})",
    )
    check(
        "insa" in education_after_str or "toulouse" in education_after_str,
        f"chunked: INSA Toulouse found in education (got {education_after})",
    )

    # Runtime sanity: chunked must finish in < 30 s (CPU, up to 4 chunks here)
    check(
        t_after < 30.0,
        f"timing: chunked extraction < 30 s (got {t_after:.1f} s)",
    )

    gain = n_ents_after - n_ents_before
    print(f"  Gain: +{gain} entities vs single-pass")
    print(f"  Overhead: +{t_after - t_before:.2f}s vs single-pass")


def test_gliner_unit():
    """Unit test: GLiNERExtractor on raw CV text (no PDF parsing)."""
    print("\n=== GLiNER unit test (raw text) ===")
    if not GLINER_PRESENT:
        print("  [SKIP] gliner package not installed -- skipping unit test")
        return

    from ai_module.nlp.gliner_extractor import GLiNERExtractor

    extractor = GLiNERExtractor()
    if not extractor._load_model():
        print("  [SKIP] GLiNER model could not be loaded (network / RAM) -- skipping")
        return

    sample_text = """Raphael MARTIN
Commercial Senior

EXPERIENCES
Responsable Commercial - DIOR (2020-2024)
Charge d affaires - ORANGE (2016-2020)
Commercial - DANONE (2014-2016)

FORMATION
Master Commerce - Universite Sorbonne (2014)
Licence Gestion - ESUP (2012)
"""
    t0 = time.time()
    result = extractor.extract(sample_text)
    elapsed = time.time() - t0
    print(f"  GLiNER output ({elapsed:.2f}s): {result}")

    check(
        _name_matches(result.get("full_name"), "Raphael", "MARTIN"),
        f"GLiNER unit: full_name contains 'Raphael MARTIN' (got {result.get('full_name')!r})",
    )
    for co in ("DIOR", "ORANGE", "DANONE"):
        companies_upper = [c.upper() for c in result.get("companies", [])]
        check(
            any(co in c for c in companies_upper),
            f"GLiNER unit: company '{co}' extracted (companies={result.get('companies')})",
        )


def test_pipeline_two_column():
    """Integration: full pipeline on cv_two_column.pdf."""
    print("\n=== Pipeline integration -- 2-column CV (Raphael MARTIN) ===")

    os.environ["USE_GLINER"] = "true"

    from app.services.cv_extractor import CVExtractionService, extract_text_from_pdf

    text = extract_text_from_pdf(TWO_COL)
    check("Raphael MARTIN" in text, "text extraction: 'Raphael MARTIN' in reflowed text")

    if not GLINER_PRESENT:
        print("  [SKIP] gliner not installed -- pipeline GLiNER checks skipped")
        print("  Running regex-only pipeline check ...")
        svc = CVExtractionService()
        result = svc.extract_from_text(text)
        candidate = svc.to_candidate_dict(result)
        name = candidate.get("full_name") or candidate.get("extracted_name")
        print(f"  Regex-only full_name: {name!r}")
        print(f"  Regex-only companies: {candidate.get('extracted_companies')!r}")
        return

    svc = CVExtractionService()
    t0 = time.time()
    result = svc.extract_from_text(text)
    elapsed = time.time() - t0
    candidate = svc.to_candidate_dict(result)

    name = candidate.get("full_name") or candidate.get("extracted_name")
    print(f"  Extracted full_name: {name!r}  ({elapsed:.2f}s)")
    check(
        _name_matches(name, "Raphael", "Martin"),
        f"pipeline 2-col: full_name ~ 'Raphael MARTIN' (got {name!r})",
    )

    import json
    companies_raw = candidate.get("extracted_companies") or "[]"
    companies = json.loads(companies_raw) if isinstance(companies_raw, str) else companies_raw
    companies_str = " ".join(str(c).upper() for c in companies)
    print(f"  Extracted companies: {companies}")
    for co in ("DIOR", "ORANGE", "DANONE"):
        check(co in companies_str, f"pipeline 2-col: company '{co}' in extracted_companies")


def test_pipeline_one_column():
    """Regression: 1-column CV must still work correctly."""
    print("\n=== Pipeline integration -- 1-column CV (Sophie BERNARD) -- regression ===")

    from app.services.cv_extractor import CVExtractionService, extract_text_from_pdf

    text = extract_text_from_pdf(ONE_COL)
    check("Sophie BERNARD" in text, "text extraction: 'Sophie BERNARD' in text")

    svc = CVExtractionService()
    t0 = time.time()
    result = svc.extract_from_text(text)
    elapsed = time.time() - t0
    candidate = svc.to_candidate_dict(result)

    name = candidate.get("full_name") or candidate.get("extracted_name")
    print(f"  Extracted full_name: {name!r}  ({elapsed:.2f}s)")
    check(
        _name_matches(name, "Sophie", "Bernard"),
        f"pipeline 1-col: full_name ~ 'Sophie BERNARD' (got {name!r})",
    )


def test_pipeline_long_cv():
    """Integration: full pipeline on cv_long.pdf (multi-chunk scenario).

    The cv_long.pdf fixture places landmark employers (AIRBUS, BOUYGUES) and
    schools (Universite Paris-Saclay, INSA Toulouse) in the SECOND HALF of the
    document, beyond the old ~6000-char / 384-token single-pass limit.

    Expected: the chunked extractor finds them all; timing must stay < 60 s.
    """
    print("\n=== Pipeline integration -- long CV (chunking scenario) ===")

    if not GLINER_PRESENT:
        print("  [SKIP] gliner not installed -- long CV GLiNER checks skipped")
        return

    os.environ["USE_GLINER"] = "true"

    from app.services.cv_extractor import CVExtractionService, extract_text_from_pdf

    text = extract_text_from_pdf(LONG_CV)
    print(f"  Extracted text length: {len(text)} chars")
    check(len(text) > 3000, f"long CV: text > 3000 chars (got {len(text)})")

    svc = CVExtractionService()
    t0 = time.time()
    result = svc.extract_from_text(text)
    elapsed = time.time() - t0
    candidate = svc.to_candidate_dict(result)

    name = candidate.get("full_name") or candidate.get("extracted_name")
    print(f"  Extracted full_name   : {name!r}  ({elapsed:.2f}s)")

    import json
    companies_raw = candidate.get("extracted_companies") or "[]"
    companies = json.loads(companies_raw) if isinstance(companies_raw, str) else companies_raw
    companies_str = " ".join(str(c).upper() for c in companies)
    print(f"  Extracted companies   : {companies}")

    ner_raw = candidate.get("ner_extraction_data") or "{}"
    import ast
    try:
        ner_data = json.loads(ner_raw)
    except Exception:
        ner_data = {}
    education = ner_data.get("education", [])
    print(f"  Extracted education   : {education}")

    # Early-document companies (always found even by old code)
    for co in ("DASSAULT", "SAFRAN"):
        check(
            co in companies_str,
            f"long CV: early company '{co}' found (companies={companies})",
        )

    # Late-document companies (only found with chunking)
    for co in ("AIRBUS", "BOUYGUES"):
        check(
            co in companies_str,
            f"long CV: late company '{co}' found by chunked extractor "
            f"(companies={companies})",
        )

    # Late-document schools
    education_str = " ".join(str(e).lower() for e in education)
    check(
        "saclay" in education_str or "paris" in education_str,
        f"long CV: late school 'Paris-Saclay' found (education={education})",
    )
    check(
        "insa" in education_str or "toulouse" in education_str,
        f"long CV: late school 'INSA Toulouse' found (education={education})",
    )

    # Timing
    check(
        elapsed < 60.0,
        f"long CV: extraction < 60 s on CPU (got {elapsed:.1f} s)",
    )


def test_fallback_without_gliner():
    """Verify USE_GLINER=false falls back to regex without crashing."""
    print("\n=== Fallback: USE_GLINER=false ===")

    os.environ["USE_GLINER"] = "false"

    from app.services.cv_extractor import CVExtractionService

    svc = CVExtractionService()
    check(not svc._use_gliner, "USE_GLINER=false: _use_gliner is False on service instance")

    sample = "Jean DUPONT\nIngenieur Logiciel\njean.dupont@example.com"
    try:
        result = svc.extract_from_text(sample)
        svc.to_candidate_dict(result)
        check(True, "USE_GLINER=false: extract_from_text does not crash")
    except Exception as exc:
        check(False, f"USE_GLINER=false: extract_from_text crashed ({exc})")

    os.environ["USE_GLINER"] = "true"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    os.makedirs(FIXTURES, exist_ok=True)
    if not os.path.exists(TWO_COL) or not os.path.exists(ONE_COL):
        print("Generating test fixtures (1-col, 2-col) ...")
        _mk.make_two_column_cv(TWO_COL)
        _mk.make_one_column_cv(ONE_COL)
    if not os.path.exists(LONG_CV):
        print("Generating long CV fixture ...")
        _mk.make_long_cv(LONG_CV)

    test_cleanup_logic()
    test_chunking_unit()
    test_chunking_before_after()
    test_gliner_unit()
    test_pipeline_two_column()
    test_pipeline_one_column()
    test_pipeline_long_cv()
    test_fallback_without_gliner()

    print()
    if _failures:
        print(f"RESULT: {len(_failures)} check(s) FAILED")
        for f in _failures:
            print("  - " + f)
        sys.exit(1)
    print("RESULT: all checks passed")
    sys.exit(0)
